### ISSUE TITLE
Test & development dependencies in package requirements

### ISSUE THREAD

**Issue by frenck** [crownstone/crownstone-lib-python-cloud#3]
This package depends/requires its test dependencies, this is not correct as it results in test dependencies being installed in production environments.

![image](https://user-images.githubusercontent.com/195327/140954819-e4cb17db-d6d8-4249-9bf2-196ab59c74c3.png)

There is no reason, for a consumer of this package, to have codecov or asynctest installed.

Additionally, the range pinned for those test dependencies are kinda strict, as they pin to minor versions instead of major versions.

**Comment by AlexDM0** [comment]
Good point regarding the test requirements, these might be better suited for a requirements_dev.txt.

I'm not sure I agree with the ranges however, especially regarding the asynctest not having reached 1.x.x. Anything below 1.0.0 can be considered in-development and can have breaking releases on every minor version.

In our experience, Python packages do not always respect SEMVER and it becomes difficult to test all versions that we're supporting if we loosen the requirements. (case in point https://github.com/crownstone/crownstone-lib-python-ble/issues/12)

This is an ongoing internal discussion as well.

What do you think @RicArch97?

**Comment by frenck** [comment]
> I'm not sure I agree with the ranges however, especially regarding the asynctest not having reached 1.x.x. Anything below 1.0.0 can be considered in-development and can have breaking releases on every minor version.

True for asyctest :)

**Comment by frenck** [comment]
> In our experience, Python packages do not always respect SEMVER 

Semver packages not even respect semver...

The point is, however, in the future, if an integration block upgrades of Home Assistant, it will lead to disabling of an integration (as recent pip versions will block).

Distrust in other packages will lead to future problems and is (IMHO) the wrong approach.
Breaking upstream packages, could as well put a breaking change in a patch release. That is also not accounted for in the current strategy, yet, you do guard for it in minor versions 🤷

**Comment by RicArch97** [comment]
Fixed in 1.4.9
